# Generated by Django 4.2.3 on 2023-07-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedirectory',
            name='contact_no_primary',
        ),
        migrations.AddField(
            model_name='employeedirectory',
            name='employee_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='json_deatils',
            field=models.JSONField(default={}),
        ),
    ]
